development:
  solr:
    hostname: localhost
    port: 8982
    min_memory: 512M
    max_memory: 1G

test:
  solr:
    hostname: localhost
    port: 8983
    log_level: OFF

staging:
  solr:
    hostname: localhost
    port: 8984
    path: /home/transparencia/public_html/staging/openwolf/currrent/solr/data/index
    log_level: WARNING
    solr_home: /home/transparencia/public_html/staging/openwolf/current/solr
  auto_commit_after_request: true

production:
  solr:
    hostname: localhost
    port: 8983
    path: /home/transparencia/public_html/openwolf/currrent/solr/data/index
    log_level: WARNING
    solr_home: /home/transparencia/public_html/openwolf/current/solr
  auto_commit_after_request: true



